name: Update website
on:
  push:
    branches: [main]
jobs:
  update_repo:
    name: Update repository
    runs-on: ubuntu-latest
    steps:
      - name: Update repository
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          script: |
            cd project5
            git pull
            cp -Rf index.html assets/ css/ js/ ../
